# Generated by Django 6.0.2 on 2026-02-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planeacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("lote", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_entrega", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planeado", "Planeado"),
                            ("diseno", "En Diseño"),
                            ("colorimetria", "En Colorimetría"),
                            ("plotter", "En Plotter"),
                            ("logistica", "En Logística"),
                            ("preparacion", "En Preparación"),
                            ("sublimado", "En Sublimado"),
                            ("rh", "En RH"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="planeado",
                        max_length=20,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
