# Generated by Django 6.0.2 on 2026-02-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diseno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colorimetria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paleta_color", models.CharField(max_length=150)),
                ("aprobado", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "diseno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colorimetrias",
                        to="diseno.diseno",
                    ),
                ),
            ],
        ),
    ]
