# Generated by Django 6.0.2 on 2026-02-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cliente", models.CharField(max_length=100)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("colorimetria", "Colorimetría"),
                            ("diseno", "Diseño"),
                            ("planeacion", "Planeación"),
                            ("logistica", "Logística"),
                            ("plotter", "Plotter"),
                            ("preparacion", "Preparación"),
                            ("sublimado", "Sublimado"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="colorimetria",
                        max_length=50,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
        ),
    ]
