# Generated by Django 6.0.2 on 2026-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="observaciones",
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="cantidad",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("proceso", "En Proceso"),
                    ("terminado", "Terminado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha",
            field=models.DateField(),
        ),
    ]
