# Generated by Django 6.0.2 on 2026-02-11 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0002_remove_ordenproduccion_cliente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="nombre",
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="producto",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Proceso", "Proceso"),
                    ("Terminado", "Terminado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Supervisor", "Supervisor"),
                            ("Operario", "Operario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
