# Generated by Django 6.0.2 on 2026-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0003_remove_ordenproduccion_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="semaforo",
            field=models.CharField(
                choices=[
                    ("Verde", "Verde"),
                    ("Amarillo", "Amarillo"),
                    ("Rojo", "Rojo"),
                ],
                default="Verde",
                max_length=10,
            ),
        ),
    ]
